reapi/extra/amxmodx/scripting/include/reapi_gamedll_const.inc

warning 200: symbol "RG_CBasePlayer_SetSpawnProtecti" is truncated to 31 characters - fixes

the bypass amxx warning 200

---

gradle.properties
reapi/extra/amxmodx/scripting/include/reapi_gamedll_const.inc
reapi/include/cssdk/dlls/API/CSPlayerWeapon.h
reapi/include/cssdk/dlls/weapons.h
reapi/src/member_list.cpp
reapi/src/member_list.h

Creating m_flBaseDamage member that change basic damage of weapons deals before any multiplier, such as hitgroup, armor, distance and bullet penetration.

Add m_flBaseDamage member

---

reapi/extra/amxmodx/scripting/include/reapi.inc
reapi/src/amx_hook.cpp
reapi/src/amx_hook.h
reapi/src/entity_callback.h
reapi/src/hook_callback.h
reapi/src/hook_manager.cpp
reapi/src/natives/natives_hookchains.cpp

Implement native to get the current hookchain handle in amxx callback

---

gradle.properties
reapi/extra/amxmodx/scripting/include/reapi_gamedll.inc
reapi/include/cssdk/dlls/gamerules.h
reapi/include/cssdk/dlls/regamedll_api.h
reapi/src/natives/natives_misc.cpp

Add a new native called "rg_plant_bomb", when called it will spawn a C4 with defined parameters and also we will be able to pass a player index or not.

Add a new native "rg_plant_bomb"

---

reapi/extra/amxmodx/scripting/include/reapi.inc
reapi/extra/amxmodx/scripting/include/reapi_gamedll_const.inc
reapi/include/cssdk/dlls/regamedll_api.h
reapi/src/hook_callback.cpp
reapi/src/hook_callback.h
reapi/src/hook_list.cpp
reapi/src/hook_list.h
reapi/src/natives/natives_hookchains.cpp
reapi/src/natives/natives_hookchains.h
reapi/src/natives/natives_misc.cpp
reapi/src/reapi_utils.cpp

* Implement "CBaseEntity::Fire<Bullets[3]|Buckshots>" hooks.
* Added new hook table "GamedllFunc_CBaseEntity".
* Added new hookchain argument type "ATYPE_VECTOR"

Implement `CBaseEntity::Fire<Bullets[3]|Buckshots>` hooks.

---

reapi/extra/amxmodx/scripting/include/reapi_gamedll_const.inc
reapi/include/cssdk/dlls/regamedll_api.h
reapi/src/hook_callback.cpp
reapi/src/hook_callback.h
reapi/src/hook_list.cpp
reapi/src/hook_list.h
reapi/version/version.h

related to https://github.com/s1lentq/ReGameDLL_CS/pull/607

Implement player `Pain`, `DeathSound` and `JoiningThink` hooks

---

reapi/extra/amxmodx/scripting/include/reapi_gamedll_const.inc
reapi/include/cssdk/dlls/regamedll_api.h
reapi/src/hook_callback.cpp
reapi/src/hook_callback.h
reapi/src/hook_list.cpp
reapi/src/hook_list.h

Related to regamedll pull: https://github.com/s1lentq/ReGameDLL_CS/pull/667

Implement `RG_CBasePlayer_Observer_FindNextPlayer` hook 

---

reapi/extra/amxmodx/scripting/include/reapi_engine_const.inc
reapi/include/cssdk/engine/rehlds_api.h
reapi/src/hook_callback.cpp
reapi/src/hook_callback.h
reapi/src/hook_list.cpp
reapi/src/hook_list.h
reapi/version/version.h

Related to https://github.com/dreamstalker/rehlds/pull/951

Implement RH_SV_AllowPhysent hook

---

reapi/src/natives/natives_misc.cpp

Add player team check to avoid unexpected behavior

`rg_give_defusekit()`: Add player team check

---

reapi/extra/amxmodx/scripting/include/cssdk_const.inc

ITDB_PARALYZE enum
according to:
Rehlds: https://github.com/dreamstalker/rehlds/blob/6a916d766b2f766ed9a45f9f008b3f7b737e3c89/rehlds/dlls/cbase.h#L651-L659
Regamedll:
https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/basemonster.h#L35-L46

Fix ``TimeBasedDamage enum`` typo at cssdk_const.inc

---

reapi/extra/amxmodx/scripting/include/reapi_gamedll.inc
reapi/include/cssdk/dlls/API/CSPlayer.h
reapi/src/natives/natives_misc.cpp

- Updated the return logic of rg_drop_item to return the index of the created weapon box
- Updated the return logic of rg_drop_items_by_slot

Updated the return logic of rg_drop_item and rg_drop_items_by_slot

---

reapi/extra/amxmodx/scripting/include/reapi_gamedll.inc
reapi/include/cssdk/dlls/gamerules.h
reapi/src/natives/natives_misc.cpp

Fixes https://github.com/s1lentq/reapi/issues/287

fix(rg_transfer_c4): prevent C4 destruction on arg receiver = 0

---

reapi/extra/amxmodx/scripting/include/cssdk_const.inc
reapi/extra/amxmodx/scripting/include/reapi_gamedll_const.inc
reapi/include/cssdk/dlls/API/CSEntity.h
reapi/include/cssdk/dlls/API/CSPlayer.h
reapi/include/cssdk/dlls/API/CSPlayerItem.h
reapi/include/cssdk/dlls/API/CSPlayerWeapon.h
reapi/include/cssdk/dlls/regamedll_api.h
reapi/include/cssdk/public/utlarray.h
reapi/msvc/reapi.vcxproj
reapi/msvc/reapi.vcxproj.filters
reapi/src/member_list.cpp
reapi/src/member_list.h

- Updated: 
- CSEntity.h: new members, offset table changed
- CSPlayer.h: new members, unused methods cleaned
- CSPlayerItem.h: vfunc update
- CSPlayerWeapon.h: vfunc added
- regamedll_api.h: latests hooks added
- Added utlarray.h (CSPlayer members)
- Renamed m_bHasSecondaryAttack member to m_iStateSecondaryAttack (with API compat in AMXX includes)
- Added CSPlayer members from last updates

Headers update, rename m_bHasSecondaryAttack, CSPlayer member additions

---

reapi/extra/amxmodx/scripting/include/reapi_gamedll_const.inc
reapi/include/cssdk/dlls/regamedll_api.h
reapi/src/hook_callback.cpp
reapi/src/hook_callback.h

CSGameRules::GiveC4 return type changed in headers but not in hook callbacks files.

Fix GiveC4 hook callback return type

---

reapi/extra/amxmodx/scripting/include/cssdk_const.inc
reapi/extra/amxmodx/scripting/include/reapi_gamedll.inc
reapi/src/natives/natives_helper.h
reapi/src/natives/natives_misc.cpp

Added the following natives to the ReAPI module:
- `rg_spawn_grenade`
- `rg_create_weaponbox`
- `rg_remove_entity`
- `rg_decal_trace`
- `rg_emit_texture_sound`
- `rg_add_ammo_registry`
- `rg_weapon_deploy`
- `rg_weapon_reload`
- `rg_weapon_shotgun_reload`
- `rg_weapon_send_animation`
- `rg_weapon_kickback`
- `rg_switch_best_weapon`
- `rg_disappear`
- `rg_set_observer_mode`
- `rg_death_notice`

API upgrade: 15 new natives

---

reapi/extra/amxmodx/scripting/include/reapi_gamedll_const.inc
reapi/src/natives/natives_misc.cpp
reapi/src/natives/natives_misc.h

feat: add WI_SLOT for rg_get_weapon_info

---

reapi/extra/amxmodx/scripting/include/cssdk_const.inc
reapi/extra/amxmodx/scripting/include/reapi_gamedll.inc
reapi/extra/amxmodx/scripting/include/reapi_gamedll_const.inc
reapi/include/cssdk/dlls/gamerules.h
reapi/src/hook_callback.cpp
reapi/src/hook_callback.h
reapi/src/hook_list.cpp
reapi/src/hook_list.h
reapi/src/natives/natives_misc.cpp
reapi/src/type_conversion.h

Related to https://github.com/s1lentq/ReGameDLL_CS/pull/858

`API`: Implement `RG_CSGameRules_SendDeathMessage` hook and `rg_send_death_message` native

---

reapi/extra/amxmodx/scripting/include/reapi_engine_const.inc
reapi/include/cssdk/engine/rehlds_api.h
reapi/src/hook_callback.cpp
reapi/src/hook_callback.h
reapi/src/hook_list.cpp
reapi/src/hook_list.h

Useful to create a custom resource list when requested by a client or to allow multiple download url setup.
Example:
```
/* Sublime AMXX Editor v4.2 */
#include <amxmodx>
#include <reapi>
#include <geoip>
new g_pCvar
new g_szCvar[64]
public plugin_init()
{
RegisterHookChain(RH_SV_SendResources, "RH_SV_SendResources_Pre")
RegisterHookChain(RH_SV_SendResources, "RH_SV_SendResources_Post", 1)
}
public plugin_precache()
{
server_cmd("exec server.cfg")
server_exec()
g_pCvar = get_cvar_pointer("sv_downloadurl")
get_pcvar_string(g_pCvar, g_szCvar, charsmax(g_szCvar))
}
public RH_SV_SendResources_Post()
{
RequestFrame("SV_SendResFrame")
}
public SV_SendResFrame()
{
new szCvar[64]
set_pcvar_string(g_pCvar, g_szCvar)
get_pcvar_string(g_pCvar, szCvar, charsmax(szCvar))
}
public …
```

Implement `RH_SV_SendResources` hook

---

reapi/extra/amxmodx/scripting/include/reapi_gamedll.inc
reapi/include/cssdk/dlls/API/CSPlayer.h
reapi/src/natives/natives_misc.cpp

Tested✔
```cpp
#include <amxmodx>
#include <reapi>
public plugin_init()
{
register_clcmd("say .fnp", "cmd_fnp");
RegisterHookChain(RG_CBasePlayer_Observer_FindNextPlayer, "RG_CBasePlayer_Observer_FindNextPlayer_Pre", false);
}
public RG_CBasePlayer_Observer_FindNextPlayer_Pre(const this, bool:bReverse, name[])
{
client_print(this, print_chat, "FindNextPlayer: bReverse(%d), name(%s)", bReverse, name);
}
public cmd_fnp(const index)
{
if (!(get_member(index, m_afPhysicsFlags) & PFLAG_OBSERVER))
{
client_print(index, print_chat, "YOUR ARE NOT A OBSERVER");
return PLUGIN_HANDLED;
}
client_print(index, print_chat, "YOU DID");
rg_observer_find_next_player(index, true, "");
return PLUGIN_HANDLED;
}
```

Add new native `rg_observer_find_next_player`

---

.github/workflows/build.yml
reapi/version/appversion.bat

+ added signing
+ migrated to windows-2025 runner
+ wmic deprecated and migrated to ps

ci-build updated

---

reapi/extra/amxmodx/scripting/include/reapi_gamedll.inc
reapi/src/hook_callback.cpp
reapi/src/natives/natives_misc.cpp

Fix CreateWeaponBox crash on undefined owner
